services:
  # OpenMRS MySQL - 안정화 설정
  openmrs-mysql:
    image: mysql:8.0
    container_name: openmrs-mysql
    hostname: openmrs-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Admin123
      MYSQL_DATABASE: openmrs
      MYSQL_USER: openmrs
      MYSQL_PASSWORD: Admin123
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    volumes:
      - openmrs_mysql_data:/var/lib/mysql
    networks:
      medical-network:
        ipv4_address: 172.20.0.10
        aliases:
          - mysql-server
          - openmrs-db
    restart: unless-stopped
    command: [
      "--character-set-server=utf8",
      "--collation-server=utf8_general_ci",
      "--skip-character-set-client-handshake",
      "--sql-mode=STRICT_TRANS_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    ]

  # OpenMRS Web Application
  openmrs-server:
    image: openmrs/openmrs-reference-application-distro:latest
    container_name: openmrs-server
    hostname: openmrs-server
    depends_on:
      - openmrs-mysql
    environment:
      DB_DATABASE: openmrs
      DB_HOST: openmrs-mysql
      DB_PORT: 3306
      DB_USERNAME: openmrs
      DB_PASSWORD: Admin123
      DB_CREATE_TABLES: "true"
      DB_AUTO_UPDATE: "true"
      MODULE_WEB_ADMIN: "true"
    ports:
      - "8082:8080"
    volumes:
      - openmrs_data:/openmrs/data
    networks:
      medical-network:
        ipv4_address: 172.20.0.11
        aliases:
          - openmrs-app
    restart: unless-stopped

  # MariaDB (메인 애플리케이션용)
  mariadb:
    image: mariadb:10.11
    container_name: mariadb-server
    hostname: mariadb-server
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: medical_platform
      MYSQL_USER: medical_user
      MYSQL_PASSWORD: medical_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      medical-network:
        ipv4_address: 172.20.0.20
        aliases:
          - main-db
    restart: unless-stopped

  # PostgreSQL (Orthanc용)
  orthanc-postgres:
    image: postgres:14
    container_name: orthanc-postgres
    hostname: orthanc-postgres
    environment:
      POSTGRES_DB: orthanc
      POSTGRES_USER: orthanc
      POSTGRES_PASSWORD: orthanc
    ports:
      - "5432:5432"
    volumes:
      - orthanc_postgres_data:/var/lib/postgresql/data
    networks:
      medical-network:
        ipv4_address: 172.20.0.30
        aliases:
          - postgres-db
          - orthanc-db
    restart: unless-stopped

  # Orthanc DICOM Server - 웹 인터페이스 포함 이미지로 변경
  orthanc:
    image: orthancteam/orthanc:24.4.0
    container_name: orthanc-server
    hostname: orthanc-server
    depends_on:
      - orthanc-postgres
    ports:
      - "8042:8042"
      - "4242:4242"
    volumes:
      - orthanc_data:/var/lib/orthanc/db
      - ./orthanc-config/orthanc.json:/etc/orthanc/orthanc.json:ro
    networks:
      medical-network:
        ipv4_address: 172.20.0.31
        aliases:
          - orthanc-app
    restart: unless-stopped

  # MongoDB
  mongodb:
    image: mongo:6.0
    container_name: mongodb-server
    hostname: mongodb-server
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      medical-network:
        ipv4_address: 172.20.0.40
        aliases:
          - mongo-db
    restart: unless-stopped

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    hostname: phpmyadmin
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb-server
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
    networks:
      medical-network:
        ipv4_address: 172.20.0.50
        aliases:
          - phpmyadmin-app
    restart: unless-stopped

# 🔥 수정된 네트워크 정의 - 사용자 정의 서브넷 추가
networks:
  medical-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

volumes:
  openmrs_mysql_data:
  openmrs_data:
  mariadb_data:
  orthanc_postgres_data:
  orthanc_data:
  mongodb_data: